[package]
name = "zswap-math-libary"
version = "0.1.0"
edition = "2021"

[profile.release]
overflow-checks = true
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
near-sdk="4.1.1"
ethnum="1.3.2"